language: erlang
otp_release:
  - R15B03
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpam0g-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./rebar compile && ./rebar skip_deps=true ct
