language: erlang
otp_release:
  - R15B03
env:
  global:
    - secure: "jjLA3RJDFkLNrQezOVevOyXUbjh1wt/ILx5VF0xEQpIN78rZc5qYbIQd53+6\n902+jtDD23SY6vNqRSJTLdgxR9gqHvbs7KnQN6jP/BeMHF9WvWNmw6x0h6Uu\n08CvrcaTRmF5KYkPojcATwL6fdXYn+Ijh4mfl8hGFlRCQkxnIAQ="
install: true
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpam0g-dev
script: make test-app
after_script: rsync --recursive --delete test/logs/ travis@thestaticvoid.com::wfd_logs
